# Generated by Django 4.1.1 on 2022-09-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_adderss',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
