# Generated by Django 4.1.1 on 2022-09-28 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_order_delivery_adderss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_adderss',
            new_name='delivery_address',
        ),
    ]
